version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  backend:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - eb/setup
      - run:
          name: Back-End deploy AWS EB
          command: |
            cd server
            ls
            eb create udacity-fullstack-backend-env || true
            eb use udacity-fullstack-backend-env
            eb setenv NODE_ENV=PROD
            eb deploy
            eb status
  frontend:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build      
      - eb/setup
      - run:
          name: Front-End deploy AWS EB
          command: |
            cd client
            ls
            eb create udacity-fullstack-frontend-env || true
            eb use udacity-fullstack-frontend-env
            eb setenv NODE_ENV=PROD
            eb deploy
            eb status
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - backend:
          context: udacity-fullstack-aws
      - frontend:
          context: udacity-fullstack-aws
          # activate if runs smoothly
          # requires:
          #   - backend