version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
  eb/deploy:
    context: udacity-fullstack-aws
    environment-name: udacity-fullstack-cicd-env
    filters:
      branches:
        only:
          - main
    label: version-1.0
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install:
          install-yarn: true
          node-version: '16.13'
workflows:
  version: 2
  pipeline: # name of workflow
    jobs: # list the jobs to to run.
      - build
      - eb/deploy