version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
  eb-backend:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          name: deploy EB
          command: |
            cd server
            eb create udacity-fullstack-backend-env || true
            eb use udacity-fullstack-backend-env
            eb setenv NODE_ENV=PROD
            eb deploy
            eb status
  eb-frontend:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          name: deploy EB
          command: |
            cd client
            eb create udacity-fullstack-frontend-env || true
            eb use udacity-fullstack-frontend-env
            eb deploy
            eb status
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - build
      - eb-backend:
          context: udacity-fullstack-aws
          requires:
            - build
      - eb-frontend:
          context: udacity-fullstack-aws
          requires:
            - build